### PR TITLE
#174772209 Setup API documentation using swagger

### PR DESCRIPTION
**Pull request by Cherubln**
#### What does this PR do?
It documents APIs using swagger
#### Description of Task to be completed?

- Have swagger UI working

- Test endpoints using swagger

#### How should this be manually tested?

1. git clone the repo (https://github.com/atlp-rwanda/wolves-bn-backend.git) then cd into it.

1. run `npm install`

1. run `npm start`

1. open browser on http://localhost:3000/api-docs/

#### What are the relevant pivotal tracker stories?
[#174772209](https://www.pivotaltracker.com/story/show/174772209)
#### Screenshot
Annotation

### CODE REVIEW

**Comment by nraufu** [comment]
LGTM

**Review by IreneRukumbuzi — APPROVED** [review]

**Comment by IreneRukumbuzi** [comment]
Looks good to me

**Review by Nosenti — APPROVED** [review]
Looks good

**Review by nraufu — APPROVED** [review]
nice work @Cherubln .

**Comment by T2Wil** [comment]
nice work @Cherubln

**Pull request merged**
