### PR TITLE
#174772215 adding log in option for users

### PR DESCRIPTION
**Pull request by Anisieu**
### What does this PR do?
- Adds the user log in
### What are the tasks to be completed?
-  A user  should be able to login using their email and password.
### How should this be manually tested?
-  git clone the application URL(https://github.com/atlp-rwanda/wolves-bn-backend.git)
- npm run dev and post on localhost:3000/api/users/signin

image

 image

### What are the relevant Pivotal tracker stories?
-  #174772215

### CODE REVIEW

**Comment by istafrica-dennw** [comment]
@Anisieu You tests have dropped the overall coverages

**Review by IreneRukumbuzi — CHANGES_REQUESTED** [review]
Nice Work @Anisieu. But, Please check that test

**Comment by IreneRukumbuzi** [comment]
Nice Work @Anisieu

**Review by Thom-IT — APPROVED** [review]
nice work @Anisieu .

**Comment by T2Wil** [comment]
Hello @Anisieu , 
I am having trouble testing the endpoint. 
I can't know which keys I should pass in the request body; please specify them in the PR description and/or provide a screenshot of the feature being tested in postman.

**Comment by T2Wil** [comment]
Replace the signin url link in the documentation with the right one.

**Pull request merged**
