### PR TITLE
#174772216 User authentication via facebook and google

### PR DESCRIPTION
**Pull request by Cherubln**
#### What does this PR do?
Add authentication via facebook and google
#### Description of Task to be completed?

Have user logged in with a google or facebook account

#### How should this be manually tested?
git clone the repo (https://github.com/atlp-rwanda/wolves-bn-backend.git)
run npm install
run npm start
login with facebook on http://localhost:3000/auth/facebook or
login  with google on http://localhost:3000/auth/google
#### What are the relevant pivotal tracker stories?
[#174772216](https://www.pivotaltracker.com/story/show/174772216)
#### Screenshots
Annotation (1)
Annotation (2)

### CODE REVIEW

**Comment by istafrica-dennw** [comment]
@Cherubln fix the conflicts. by rebasing

**Review by IreneRukumbuzi — APPROVED** [review]
Nice Work @Cherubln

**Review by nraufu — COMMENTED** [review]
@Cherubln nice work! however remember to add the used Envirnoment name into the `.en.example` file

**Review by nraufu — APPROVED** [review]
LGTM!

**Pull request merged**
